Validate Standup Details
code-mancers/gather-bot pull request #118
Opened 2022-10-20 16:48 UTC by SyedSibtainRazvi

Task Description:

Adding Express Validator to the Bot to validate Stand-up Details before saving it to the Database

2022-10-26 12:27 UTC, SujayPrabhu96 requested changes

2022-10-26 12:27 UTC, SujayPrabhu96 commented on server/src/routes/standups.router.ts
> +  body("channel").not().isEmpty(),
Check the add form in FE and see what other fields have been missed in validation

2022-10-26 12:27 UTC, SujayPrabhu96 commented on server/src/routes/standups.router.ts
> +  body("channel").not().isEmpty(),
Move these validators to `/helpers/standupValidation.ts`

2022-10-26 12:32 UTC, SujayPrabhu96 requested changes

2022-10-26 12:32 UTC, SujayPrabhu96 commented on server/src/routes/standups.router.ts
> +  body("title").isLength({ min: 5, max: 20 }),
We don't have length validation in FE, so you can remove it and validate if the title is present

2022-10-26 16:24 UTC, SyedSibtainRazvi commented on server/src/routes/standups.router.ts
> +  body("channel").not().isEmpty(),
Done

2022-10-26 16:24 UTC, SyedSibtainRazvi commented on server/src/routes/standups.router.ts
> +  body("title").isLength({ min: 5, max: 20 }),
Changed

2022-10-26 16:54 UTC, SujayPrabhu96 requested changes

2022-10-26 16:54 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +export const validateStandup = [
Is the prettier installed ?

2022-10-26 16:54 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +    body("date").isISO8601().toDate(),
There is no `date` field sent in FE request. Please check the fields from here: https://github.com/code-mancers/gather-bot/blob/main/server/src/services/standups.service.ts#L27-L32

2022-10-26 16:54 UTC, SujayPrabhu96 commented on server/src/routes/standups.router.ts
> +  else {
Prettier issue

2022-10-27 04:51 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +export const validateStandup = [
Yes

2022-10-27 05:07 UTC, SyedSibtainRazvi commented on server/src/routes/standups.router.ts
> +  else {
Fixed

2022-10-27 05:07 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +    body("date").isISO8601().toDate(),
Done

2022-10-27 06:03 UTC, SujayPrabhu96 requested changes

2022-10-27 06:06 UTC, SyedSibtainRazvi commented on server/src/routes/standups.router.ts
> +  if (!errors.isEmpty()) {
Understood and corrected

2022-10-27 06:08 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("days").isISO8601().toDate(),
Corrected

2022-10-27 13:09 UTC, SujayPrabhu96 requested changes

2022-10-27 15:39 UTC, SyedSibtainRazvi commented on server/src/controllers/standup.controller.ts
> +    console.log(req);
Removed

2022-10-27 17:51 UTC, SujayPrabhu96 requested changes

2022-10-27 17:51 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  check("questions.*").not().isEmpty().trim().isLength({ min: 1, max: 10}),
I have couple of questions
- What does `check("questions.*")` mean ? (Similarly for `members` and `days`)
- We have not set any limit for number of questions. So, do we need to set `isLength({})` ?

> check("days.*").trim().isInt().isLength({ min: 0, max: 6 })
- `days` is an array. So, does `isInt` holds good in this case or do we have any methods like `isArray`

2022-10-27 17:51 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  body("title").not().isEmpty(),
We can also send custom error message:
https://express-validator.github.io/docs/validation-chain-api.html#notempty
https://express-validator.github.io/docs/validation-chain-api.html#notempty

```suggestion
  body("title").trim().notEmpty().withMessage('Title should not be empty'),
```

2022-10-27 18:05 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("title").not().isEmpty(),
Yes, custom messages can be added

2022-10-27 18:09 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  check("questions.*").not().isEmpty().trim().isLength({ min: 1, max: 10}),
We can use isArray() method as well for days and provide length as well.
Using check("questions.*") is something that I read in a blog while using express-validator, however we can stick to checking in the body.

Length can be removed for the questions as well

2022-10-28 04:21 UTC, SujayPrabhu96 requested changes
Add custom messages for all the fields

2022-10-28 04:21 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  body("members").notEmpty().trim().isLength({ min: 1, max: 20 }),
There are no limits on members as well

2022-10-28 04:21 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  body("days").trim().isArray().isLength({ min: 0, max: 6 }),
```suggestion
  body("days").trim().isArray().isLength({ min: 1, max: 6 }),
```

2022-10-28 05:26 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("members").notEmpty().trim().isLength({ min: 1, max: 20 }),
Sure, will correct it and add a custom message for all fields.

2022-10-28 05:26 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("days").trim().isArray().isLength({ min: 0, max: 6 }),
Corrected

2022-10-28 11:40 UTC, SyedSibtainRazvi commented
![Validation Unsuccessful](https://user-images.githubusercontent.com/85342058/198578824-d8beed6a-0144-49cc-a441-7f4ecab9c4b1.png)

2022-10-28 12:01 UTC, SujayPrabhu96 requested changes

2022-10-28 12:01 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +    .withMessage("Please enter at least one channel?"),
```suggestion
    .withMessage("Please enter at least one channel"),
```

2022-10-28 12:01 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  body("days").notEmpty().isArray({min: 1}).withMessage("Please enter a valid day"),
Is the prettier working ? 🤔

2022-10-28 12:01 UTC, SujayPrabhu96 commented on server/src/helpers/standupValidation.ts
> +  body("members").notEmpty().withMessage("Members cannot be empty"),
Can we have `isArray({ min: 1 })` for questions and members ?

2022-10-28 12:04 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("days").notEmpty().isArray({min: 1}).withMessage("Please enter a valid day"),
It works, need to reconfigure it. Some issues

2022-10-28 12:04 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +    .withMessage("Please enter at least one channel?"),
Corrected

2022-10-28 12:06 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +    .trim()
Yes, checked and corrected

2022-10-28 12:07 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +    .withMessage("Please enter atleast one question?"),
Corrected

2022-10-28 14:08 UTC, SyedSibtainRazvi commented on server/src/helpers/standupValidation.ts
> +  body("members").notEmpty().withMessage("Members cannot be empty"),
I need to check if `isArray` will work on an array of objects, I assume it might now work

2022-10-30 04:07 UTC, SujayPrabhu96 approved these changes

2022-10-30 04:08 UTC, merged