removed days table from prisma model and added it as an array field
code-mancers/gather-bot pull request #126
Opened 2022-10-28 13:12 UTC by ayushdevelop

# functionalities Added or Changed

-  removed days table from prisma model and added it as an array field

2022-11-21 17:28 UTC, SujayPrabhu96 requested changes

2022-11-21 17:28 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +import { Context } from "../__tests__/prismaTestUtils/context";
We are not using context approach instead we are using singleton class for both service and test.
Refer this PR: https://github.com/code-mancers/gather-bot/pull/144

2022-11-21 17:31 UTC, SujayPrabhu96 requested changes

2022-11-21 17:31 UTC, SujayPrabhu96 commented on server/__mock__/standup.mock.ts
> +export const mockCreateStandupData = {
I wouldn't suggest putting these data in mock file as this would be difficult to read and understand the tests. Other than `mockStandupData` we can move all the values to their respective test files

2022-11-21 17:32 UTC, ayushdevelop commented on server/__mock__/standup.mock.ts
> +export const mockCreateStandupData = {
Okay understood, moving the data to respective tests

2022-11-21 17:49 UTC, SujayPrabhu96 requested changes

2022-11-21 17:49 UTC, SujayPrabhu96 commented on server/__mock__/standup.mock.ts
> +export const mockCreateStandupData = {
remove these variables

2022-11-21 17:53 UTC, ayushdevelop commented on server/__mock__/standup.mock.ts
> +export const mockCreateStandupData = {
both of these?, mockStandupData  is being used in the tests, reason I have kept it in mock file is because it has few elements that is making the code look bloated in tests file?

2022-11-21 17:54 UTC, SujayPrabhu96 commented on server/__mock__/standup.mock.ts
> +export const mockCreateStandupData = {
Okay

2022-11-21 17:54 UTC, SujayPrabhu96 approved these changes

2022-11-22 04:44 UTC, SujayPrabhu96 approved these changes

2022-11-22 04:44 UTC, merged