One standup per channel
code-mancers/gather-bot pull request #144
Opened 2022-11-07 13:12 UTC by SyedSibtainRazvi

# Related Issue

- https://github.com/code-mancers/gather-bot/issues/93

# functionalities Added or Changed

- Added a feature to check whether a standup is available in the DB
- If available, throw error standup already created

# Additional Info

-In g-bot when a standup is been already created for a channel , then another standup should not be created in the existing channel

# Checklist

- [ ] Tests
- [ ] Uploaded screenshots

# Screenshots
![StandupAlreadyCreated](https://user-images.githubusercontent.com/85342058/200318919-2663f6d9-fad2-40dd-8a64-417794588635.png)

2022-11-09 13:41 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +    const oneStandup = await prisma.channel.findMany({
Create new method `findStandup` and put the logic of finding the standup in that method

2022-11-09 13:45 UTC, SujayPrabhu96 requested changes
Add test cases please

2022-11-09 13:45 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +        slackChannelId: channel.id,
We need to also consider `workspace`. Because multiple standups from different workspaces can be from `general` channel

2022-11-10 07:11 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +        slackChannelId: channel.id,
Done

2022-11-10 07:26 UTC, SujayPrabhu96 requested changes

2022-11-10 07:26 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +  const findStandupInChannel = await prisma.channel.findMany({
Should be a method

2022-11-10 07:26 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +  const findStandupInWorkspace = await prisma.workspace.findMany({
Should be a method

2022-11-10 07:26 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +      slackChannelId: channel.id,
Where are we getting this channel.id from ?

2022-11-10 07:26 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +      slackWorkspaceId: workspaceData.id,
From where are we getting workspace data ?

2022-11-10 08:55 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +  const findStandupInWorkspace = await prisma.workspace.findMany({
Done

2022-11-10 08:55 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +  const findStandupInChannel = await prisma.channel.findMany({
Done

2022-11-10 08:55 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +      slackChannelId: channel.id,
Changed and now getting from params

2022-11-10 08:55 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +      slackWorkspaceId: workspaceData.id,
Changed and now getting from params

2022-11-10 14:53 UTC, SujayPrabhu96 requested changes

2022-11-10 15:37 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +const findStandup = async (channelId: string, workspaceDataId: any) => {
Done

2022-11-10 15:38 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +    const findStandups = await findStandup(channel.id, workspaceData.id);
Done

2022-11-13 12:17 UTC, SujayPrabhu96 requested changes

2022-11-13 12:17 UTC, SujayPrabhu96 commented on server/src/__tests__/standup/standups.service.test.ts
> +const availableStandups = async (
Why are we defining a method in tests ?

2022-11-13 15:13 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standups.service.test.ts
> +const availableStandups = async (
I took reference from the same file, where we have methods for `fetchAllStandups` and `createStandups`

2022-11-14 04:48 UTC, SujayPrabhu96 requested changes

2022-11-14 04:48 UTC, SujayPrabhu96 commented on server/src/__tests__/standup/standups.service.test.ts
> +import { resolveSoa } from "dns";
remove

2022-11-18 17:19 UTC, SujayPrabhu96 requested changes

2022-11-18 17:19 UTC, SujayPrabhu96 commented on server/src/controllers/standup.controller.ts
> +let ctx: Context;
remove and while passing params we can do `ctx: Context`

2022-11-18 17:19 UTC, SujayPrabhu96 commented on server/src/controllers/standup.controller.ts
> +let ctx: Context;
Do not leave multiple line spaces

2022-11-18 17:19 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +let ctx: Context;
remove

2022-11-18 17:26 UTC, SyedSibtainRazvi commented on server/src/controllers/standup.controller.ts
> +let ctx: Context;
Okay, will do it this way

2022-11-18 17:26 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +let ctx: Context;
Sure, will remove it

2022-11-21 06:04 UTC, SujayPrabhu96 requested changes

2022-11-21 06:04 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +    return prisma.channel.findMany({
```suggestion
    return ctx.prisma.channel.findMany({
```

2022-11-21 06:38 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +    return prisma.channel.findMany({
It is a method used inside the Post standup, we are passing the ctx to the main function. Do we need to pass it to this function as well as it is used inside it

2022-11-21 06:40 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +    return prisma.channel.findMany({
Yes, because we need this method to fetch standup based on channel id & workspace id (eg for slash command feature). So, we can pass context here

2022-11-21 08:54 UTC, nishanthmathiyazhagan9704 commented
Test , ignore 
Closes #93

2022-11-21 11:47 UTC, SujayPrabhu96 requested changes

2022-11-21 11:47 UTC, SujayPrabhu96 commented on server/src/__tests__/standup/standups.service.test.ts
>  describe("POST / standups", () => {
Test cases should be like documentation
```
describe("POST /standups", () => {
   test("when all the required fields are present", () => {
      test("should save standup to the database", () => { 
         // test
     })
     test("when standup is not present for the selected channel and workspace", () => {
            test("should save standup to the database", () => {
               // test
            })
      })
      test("when standup is already present for the selected channel and workspace", () => {
            test("should throw error", () => {
               // test
            })
      })
   })
})
```

2022-11-21 11:53 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standups.service.test.ts
>  describe("POST / standups", () => {
Updated and will remember it going forward

2022-11-21 12:11 UTC, SujayPrabhu96 approved these changes

2022-11-21 12:12 UTC, merged