Github Actions
code-mancers/gather-bot pull request #154
Opened 2022-11-14 12:00 UTC by SyedSibtainRazvi

# Related Issue
https://github.com/orgs/code-mancers/projects/2/views/2

# functionalities Added or Changed

- Added GitHub actions to build and test in Node

# Additional Info

- Every time a PR is opened, test cases should run on the PR
Use Postgres for running test cases
PR will be reviewed once the test cases are passed

# Checklist

- [ ] Tests
- [ ] Uploaded screenshots

# Screenshots

2022-11-15 11:20 UTC, SujayPrabhu96 requested changes

2022-11-15 11:20 UTC, SujayPrabhu96 commented on .github/workflows/g-bot-actions.yml
> +        run: node client.js
Do we have client.js file in our file ?

2022-11-15 11:47 UTC, SyedSibtainRazvi commented on .github/workflows/g-bot-actions.yml
> +        run: node client.js
No, removing it

2022-11-17 06:50 UTC, SujayPrabhu96 requested changes
We need to specify the database
Reference: https://gist.github.com/2color/537f8ef13ecec80059abb007839a6878

2022-11-17 07:58 UTC, SujayPrabhu96 commented
> > We need to specify the database Reference: https://gist.github.com/2color/537f8ef13ecec80059abb007839a6878
> 
> I have a question here. I saw the reference and we need to specify the database, however why localhost DB? And since we are using Prisma then we need to add that as well.

No, its a reference. You can get github action to set up Postgres in Marketplace

2022-11-17 09:29 UTC, SujayPrabhu96 commented on .github/workflows/g-bot-actions.yml
> +        with:5
Why 5 ?

2022-11-17 11:11 UTC, SyedSibtainRazvi commented on .github/workflows/g-bot-actions.yml
> +        with:5
Removed it

2022-11-17 12:11 UTC, SujayPrabhu96 approved these changes

2022-11-17 12:11 UTC, merged