refactor: standup command changed for dev
code-mancers/gather-bot pull request #166
Opened 2022-11-16 09:49 UTC by SyedSibtainRazvi

# Related Issue

- https://github.com/code-mancers/gather-bot/issues/155

# functionalities Added or Changed

- changed the standup command for dev env to `/standupdev`

# Additional Info

- Updated the command in slack in manage my apps as well
# Checklist

- [ ] Tests
- [ ] Uploaded screenshots

# Screenshots
![slashcommand](https://user-images.githubusercontent.com/85342058/202145956-5850dd11-953c-45bd-8ce2-e9b6921253f6.png)

2022-11-18 17:02 UTC, SujayPrabhu96 requested changes

2022-11-18 17:02 UTC, SujayPrabhu96 commented on server/src/listeners/commands/index.ts
> +  } else if (env === "prod") {
```suggestion
  } else if (env === "production") {
```

2022-11-18 17:03 UTC, SyedSibtainRazvi commented on server/src/listeners/commands/index.ts
> +  } else if (env === "prod") {
Fixed

2022-11-21 06:05 UTC, SujayPrabhu96 approved these changes

2022-11-21 06:05 UTC, merged