Standup filtering
code-mancers/gather-bot pull request #205
Opened 2022-11-24 07:02 UTC by SyedSibtainRazvi

# Related Issue

- https://github.com/code-mancers/gather-bot/issues/153

# functionalities Added or Changed

# Additional Info

- any additional information

# Checklist

- [ ] Tests
- [ ] Uploaded screenshots

# Screenshots

2022-11-30 13:26 UTC, SujayPrabhu96 requested changes

2022-11-30 15:41 UTC, SyedSibtainRazvi commented on server/src/services/standupAvailability.ts
> +    console.log(hour);
Done

2022-11-30 15:41 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standupAvailability.test.ts
> +  // test("Should throw error when standups are not available for today", async () => {
Added

2022-11-30 15:43 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standupAvailability.test.ts
> +dayjs.extend(utc);
No, it is a special case here, where we need dynamic data to be passed for original time, only then the test will pass.

2022-11-30 15:48 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standupAvailability.test.ts
> +const hour: any = new Date(`${dayjs.utc().format()}`)
Yes, can be removed

2022-11-30 15:48 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standupAvailability.test.ts
> +dayjs().format();
Removed

2022-12-01 07:42 UTC, SujayPrabhu96 requested changes

2022-12-01 07:42 UTC, SujayPrabhu96 commented on server/src/__tests__/standup/standupAvailability.test.ts
> +    prismaMock.standup.findMany.mockResolvedValue(mockStandupData);
When standup is for current+2 hours, how is `standupsAvailable()` returning the standup ?

2022-12-01 08:55 UTC, SyedSibtainRazvi commented on server/src/__tests__/standup/standupAvailability.test.ts
> +    prismaMock.standup.findMany.mockResolvedValue(mockStandupData);
It will return the standup, however, it will not go to the standups available this hour method. isn't it?

2022-12-01 09:03 UTC, SujayPrabhu96 commented on server/src/__tests__/standup/standupAvailability.test.ts
> +    expect(standupsAvailable()).resolves.toEqual(mockStandupData);
What does this line do then ?

2022-12-01 09:28 UTC, SujayPrabhu96 approved these changes

2022-12-01 09:58 UTC, SujayPrabhu96 approved these changes

2022-12-01 09:59 UTC, merged