Reminder option for Gbot
code-mancers/gather-bot pull request #215
Opened 2022-11-28 06:35 UTC by SyedSibtainRazvi

# Related Issue

- https://github.com/code-mancers/gather-bot/issues/170

# functionalities Added or Changed

- Added reminder to schema and create standup

# Additional Info

- 

# Checklist

- [ ] Tests
- [ ] Uploaded screenshots

# Screenshots
![reminder](https://user-images.githubusercontent.com/85342058/204209589-7f476f97-5748-43c9-8a3c-5783ade7f227.png)

2022-11-28 12:51 UTC, SujayPrabhu96 requested changes

2022-11-28 12:51 UTC, SujayPrabhu96 commented on server/prisma/schema.prisma
> +  reminder     Int[]
```suggestion
  reminder     Int
```

2022-11-28 14:55 UTC, SyedSibtainRazvi commented on server/prisma/schema.prisma
> +  reminder     Int[]
Resolved and updated the service as well as test cases.

2022-11-30 04:19 UTC, SujayPrabhu96 requested changes

2022-11-30 04:19 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +        reminder: reminder,
```suggestion
        reminder,
```

2022-11-30 04:19 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +    reminder: standup?.reminder,
remove optional chaining

2022-11-30 04:19 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +        reminder: reminder,
```suggestion
        reminder,
```

2022-11-30 05:34 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +        reminder: reminder,
Done

2022-11-30 05:35 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +    reminder: standup?.reminder,
Can be removed once we handled it in FE, else it says our standup is possibly null

2022-11-30 05:39 UTC, SyedSibtainRazvi commented on server/src/services/standups.service.ts
> +        reminder: reminder,
done

2022-11-30 10:27 UTC, SujayPrabhu96 approved these changes

2022-11-30 10:28 UTC, SujayPrabhu96 commented on server/src/services/standups.service.ts
> +    reminder: standup?.reminder,
Update: This has already been fixed in PR: 217

2022-11-30 10:28 UTC, merged